UnifranChat/Controllers/TrucoController.cs
using System;
using System.Web.Mvc;
using UnifranChat.Hubs;
using UnifranChat.Models.Truco.ViewModel;

namespace UnifranChat.Controllers
{
    public class TrucoController : Controller
    {
        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            JovoTruco.NomeJogador = form["txtName"];
            return View();
        }
        public ActionResult AtivaMesa(string mesa, string cartas)
        {
            var ms = new MesaViewModel(cartas)
            {
                MesaId = mesa.Split(',')[0],
                NumJogador = mesa.Split(',')[1],
                JogVez = mesa.Split(',')[2]
            };

            return View("Truco/_TrucoMesa", ms);
        }
    }
}

UnifranChat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    <style>
        #contModal {
            background-color: white;
            margin-top: 280px;
            width: 370px;
            margin-left: 40%;
            height: 100px;
        }
    </style>

    <div id="divModal2" class="modal-backdrop" style="display: none;">

    </div>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="pull-left">
                <p class="muted">Default</p>
                <div class="dropdown clearfix">
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                        <li><a tabindex="-1" href="#">Action</a></li>
                        <li><a tabindex="-1" href="#">Another action</a></li>
                        <li><a tabindex="-1" href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-submenu">
                            <a tabindex="-1" href="#">More options</a>
                            <ul class="dropdown-menu">
                                <li><a tabindex="-1" href="#">Second level link</a></li>
                                <li><a tabindex="-1" href="#">Second level link</a></li>
                                <li><a tabindex="-1" href="#">Second level link</a></li>
                                <li><a tabindex="-1" href="#">Second level link</a></li>
                                <li><a tabindex="-1" href="#">Second level link</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")
                        <ul class="ui-tabs-nav">
                            <li>Tet1</li>
                            <li>Tet1</li>
                            <li>Tet1</li>
                            <li>Tet1</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/SignalR")
    @RenderSection("scripts", required: false)
    
    <script>
        $('#btnCancelarTrc').click(function() {
            $('#divModal2').hide();
        });
    </script>
</body>
</html>

UnifranChat/Views/Shared/_LayoutTruco.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Novo Truco</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/NovoTruco.css" rel="stylesheet" />
</head>
<body ondrop="drop(event)" ondragover="allowDrop(event)">
    <div id="divModal2" class="modal-backdrop" style="display: none;">

        @using (Html.BeginForm("Index", "Truco", FormMethod.Post))
        {
            <div id="contModal" style="background-color: white">
                <div style="font-size: 16px; color: blue; text-align: center;"><b>Jogar Truco</b></div>
                <input type="text" id="txtName" name="txtName" placeholder="Insira nome Jogador" style="margin-left: 30px;margin-top: 20px" />
                <input class="btn btn-default" type="submit" value="Iniciar" @*style="margin-top: 36px"*@>
                <input class="btn btn-default" id="btnCancelarTrc" type="reset" value="Cancelar" @*style="margin-top: 36px"*@>
            </div>
        }

    </div>

    <div id="divBody">
        <script src="~/Scripts/jquery-1.10.2.js"></script>

        @RenderBody()
    </div>
    <div id="divsChats"></div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>

        $('#btnCancelarTrc').click(function () {
            $('#divModal2').hide();
        });
    </script>
    <script>
        function allowDrop(ev) {
            ev.preventDefault();
        }

        function drag(ev) {
            ev.dataTransfer.setData(this, ev.target.id);
        }

        function drop(ev) {
            ev.preventDefault();
            var data = ev.dataTransfer.getData(this);
            var a = document.getElementById(data);
            a.style.left = event.clientX + "px";
            a.style.top = event.clientY + "px";
            a.style.bottom = "auto";
        }
    </script>
</body>

</html>

UnifranChat/Views/Shared/_LoginJogo.cshtml
@model string[]

@{
    Layout = null;
}
@using (Html.BeginForm(Model[0], Model[1], FormMethod.Post))
{
    <div id="contModal" style="background-color: white">
        <div style="font-size: 16px; color: blue; text-align: center;"><b>Jogar Truco</b></div>
        <input type="text" id="txtName" name="txtName" placeholder="Insira nome Jogador" style="margin-left: 30px;margin-top: 20px" />
        <input class="btn btn-default" type="submit" value="Iniciar" @*style="margin-top: 36px"*@>
        <input class="btn btn-default" id="btnCancelarTrc" type="reset" value="Cancelar" @*style="margin-top: 36px"*@>
    </div>
}