UnifranChat/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnifranChat.Hubs;

namespace UnifranChat.Controllers
{
    public class ChatController : Controller
    {
        //
        // GET: /Chat/
        public ActionResult Index(FormCollection form)
        {
            Chat.NomeUsuario = form["txtNome"];
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult JogoVelha()
        {
            return View();
        }

	}
}

UnifranChat/Views/Chat/Index.cshtml

@{
    Layout = null;
}

<!-- Referenciando os scripts adicionados ao Bundle -->
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/SignalR")
<script src="~/signalr/hubs"></script>

<h1 id="nomeUsuario"></h1>
<label for="mensagem">Mensagem:</label><input type="text" style="width:300px;" name="mensagem" id="mensagem" maxlength="100" />
<div id="chatWindow" style="width: 100%; height: 300px; overflow: scroll; border: 1px solid grey"></div>
<select id="ddlUsuarios">
    
</select>

<script type="text/javascript">
    $(function () {
        // Declarando um proxy de referencia ao Hub
        var chatHub = $.connection.chat;

        // Criando a função que será chamada pelo Hub para distribuir as mensagens aos clientes.
        // Por convenção as chamadas aos métodos são feitas em "camelCase"
        chatHub.client.transmitirMensagem = function (apelido, msg) {

            // Area do chat
            var chatWin = $("#chatWindow");

            // Publicando a mensagem no chat
            chatWin.html(chatWin.html() + "<b>" + apelido + "</b>: " + msg + "<br />");
        };
        
        chatHub.client.carregaUsuarios = function (usuarios) {
            var usuariosFull = usuarios.split(';');
            for (var i = 0; i < usuariosFull.length; i++) {
                if ($.connection.hub.id == usuariosFull[i].split(',')[1]) {
                    $('#nomeUsuario').html("Bem Vindo " + usuariosFull[i].split(',')[0]);
                    continue;
                }

                $('#ddlUsuarios').append(new Option(usuariosFull[i].split(',')[0], usuariosFull[i].split(',')[1])); 
            }
        }
        
        chatHub.client.limpaDropdown = function () {
            $('#ddlUsuarios').html('<option value="0">Todos</option>');
        }

        // Iniciando a conexão com o Hub
        $.connection.hub.start();

        // Validando o botão enter
        $(document).keypress(function (e) {
            if (e.which == 13) {

                // Chamando o método de transmissão de mensagem no Hub
                chatHub.server.enviarMensagem($("#mensagem").val(),$('#ddlUsuarios').val());

                // Limpando o texto da mensagem.
                $("#mensagem").val("");
            }
        });
    });
</script>

UnifranChat/Views/Chat/Login.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Index","Chat"))
        {
           <p>Login:</p>
            @Html.TextBox("txtNome")  <br/>
            <input type="submit" value="Entrar"/>
        } 
    </div>
</body>
</html>