UnifranChat/Controllers/CtrlFinanceiroController.cs
using System.Web.Mvc;

namespace UnifranChat.Controllers
{
    public class CtrlFinanceiroController : Controller
    {
        // GET: CtrlFinanceiro
        public ActionResult CtrlFinanceiro()
        {
            return View();
        }
    }
}

UnifranChat/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UnifranChat.Models.NovoTruco;

namespace UnifranChat.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult ModalLgin(string metodo , string controle)
        {
            return View("_LoginJogo", (object)new[] { metodo, controle });
        }
    }
}

UnifranChat/Controllers/NovoTrucoController.cs
using System.Linq;
using System.Web.Mvc;
using UnifranChat.Hubs;
using UnifranChat.Models.NovoTruco;

namespace UnifranChat.Controllers
{
    public class NovoTrucoController : Controller
    {
        //[HttpPost]
        public ActionResult NovoTruco()//FormCollection form)
        {
            var nomeTest = "Teste";
            HubNovoTruco.NomeJogador = nomeTest;// form["txtName"];
            var cont = 1;
            while (HubNovoTruco.NovoTruco.ListUsuarios.Any(x => x.Nome == HubNovoTruco.NomeJogador))
            {
                HubNovoTruco.NomeJogador = nomeTest + "(" + cont + ")";//form["txtName"] + "(" + cont + ")";
                cont++;
            }
            return View();
        }

        public ActionResult CarregaJogo(string pagina)
        {
            var retorno = new ViewModelSalaEspera()
            {
                NovoTruco = HubNovoTruco.NovoTruco,
                PaginaSala = int.Parse(pagina)
            };
            return View("NovoTruco/_NovoTrucoMesas", retorno);
        }

        public ActionResult CarregaMesa(string idMesa, string numJogador)
        {
            var model =
                HubNovoTruco.NovoTruco.ListSalas.Select(x => x.ListaMesas.FirstOrDefault(y => y.MesaId == idMesa))
                    .FirstOrDefault();

            var viewModel = new ViewModelMesa(model, numJogador);

            return View("NovoTruco/_NovoTruco", viewModel);
        }

        public ActionResult ModalPanelControle(string idMesa, bool zeraRodada)
        {
            var mesa =
                HubNovoTruco
                    .NovoTruco.ListSalas.Select(x => x.ListaMesas).ToList()
                    .Select(x => x.FirstOrDefault(y => y.MesaId == idMesa)).FirstOrDefault();

            if (mesa != null && zeraRodada)
                mesa.PainelCtrl.ZeraRodada();

            return mesa != null
                ? View("NovoTruco/_PainelTruco", mesa.PainelCtrl)
                : null;
        }
    }
}

UnifranChat/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

UnifranChat/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

UnifranChat/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<script src="~/Scripts/jquery-1.10.2.js"></script>

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <input class="btn btn-default" type="button" id="" value="Jogar Truco" onclick="CarregarModal('Index','Truco')">
    </div>
    <div class="col-md-4">
        @Html.ActionLink("Cadastro Credito", "CtrlFinanceiro", "CtrlFinanceiro", null, new { @class = "btn btn-default" })
    </div>
    <div class="col-md-4">
        @*<input class="btn btn-default" type="button" id="" value="Jogar NovoTruco" onclick="CarregarModal('NovoTruco', 'NovoTruco')">*@
        @Html.ActionLink("Jogar Novo Truco", "NovoTruco", "NovoTruco", null, new { @class = "btn btn-default" })
    </div>
    <div id="testeDivm">
        <div class="fffT"></div>
        <div class="fffT"></div>
        <div class="fffT"></div>
        <div class="fffT"></div>
        <div class="cccc"></div>
    </div>
    <div class="col-md-4">
        <input class="btn btn-default" type="button" id="xcxcx" value="Jogar Truco">
    </div>
</div>

<script>
    function CarregarModal(act, ctrl) {
        $.get("../Home/ModalLgin", { metodo: act, controle: ctrl }).success(function (data) {
            $('#divModal2').html(data);
            $('#divModal2').show();
            $('#txtName').focus();
        });
    }
    console.log($('#testeDivm .fffT').length);
    console.log($('#testeDivm .cccc').length);

    $('#xcxcx').click(function () {
        $('#testeDivm div[class~="fffT"]:nth-child(1)').remove();
        console.log($('#testeDivm .fffT').length);
        console.log($('#testeDivm .cccc').length);
    })
    

</script>